## CI - Player And Plugin Tests
name: Player And Plugin Tests
run-name: Player And Plugin Tests

on:
  pull_request:
    branches:
      - "*"

jobs:
  task-runner:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - task: "build"
            yarn-run-to-execute: "build"
          - task: "test"
            yarn-run-to-execute: "test"
          - task: "type-check"
            yarn-run-to-execute: "type-check"
          # Add more tasks as needed

    steps:
      - uses: actions/checkout@v3

      - name: Run ${{ matrix.task }}
        uses: kaltura/ovp-pipelines-pub/.github/workflows/player_tests.yaml@master
        with:
          node-version: '20.x'
          yarn-run-to-execute: ${{ matrix.yarn-run-to-execute }}

  notification:
    if: always()
    uses: kaltura/ovp-pipelines-pub/.github/workflows/notification.yaml@master
    needs: [task-runner]
    secrets:
      PLAYER_MSTEAMS_WEBHOOK: ${{ secrets.PLAYER_MSTEAMS_WEBHOOK }}
    with:
      failure-status: ${{ contains(needs.*.result, 'failure') }}
      cancelled-status: ${{ contains(needs.*.result, 'cancelled') }}
      is-test: 'true'
