## Canary CI/CD
name: Canary
run-name: Canary

on:
  push:
    branches:
      - master

jobs:
  canary:
    if: ${{ github.actor != 'PlaykitJs-Bot' }}
    uses: kaltura/playkit-js-common/.github/workflows/canary_full_flow_dependency.yaml@0acc2c19c8fa88c798023e9b2ec76b806cacec03
    secrets: inherit
    with:
      schema-type: "playerV3Versions"
      tests-yarn-run-to-execute: 'build eslint flow test'
